# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_mkdocs_test',
                'doc_host': 'https://harishmohanraj.github.io',
                'git_url': 'https://github.com/harishmohanraj/nbdev_mkdocs_test',
                'lib_path': 'nbdev_mkdocs_test'},
  'syms': { 'nbdev_mkdocs_test.core': { 'nbdev_mkdocs_test.core.HelloSayer': ('core.html#hellosayer', 'nbdev_mkdocs_test/core.py'),
                                        'nbdev_mkdocs_test.core.HelloSayer.__init__': ( 'core.html#hellosayer.__init__',
                                                                                        'nbdev_mkdocs_test/core.py'),
                                        'nbdev_mkdocs_test.core.HelloSayer.class_method': ( 'core.html#hellosayer.class_method',
                                                                                            'nbdev_mkdocs_test/core.py'),
                                        'nbdev_mkdocs_test.core.HelloSayer.instance_method': ( 'core.html#hellosayer.instance_method',
                                                                                               'nbdev_mkdocs_test/core.py'),
                                        'nbdev_mkdocs_test.core.HelloSayer.static_method': ( 'core.html#hellosayer.static_method',
                                                                                             'nbdev_mkdocs_test/core.py'),
                                        'nbdev_mkdocs_test.core.foo': ('core.html#foo', 'nbdev_mkdocs_test/core.py')}}}
