# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_mkdocs_test',
                'doc_host': 'https://harishmohanraj.github.io',
                'git_url': 'https://github.com/harishmohanraj/nbdev_mkdocs_test',
                'lib_path': 'nbdev_mkdocs_test'},
  'syms': {'nbdev_mkdocs_test.core': {'nbdev_mkdocs_test.core.foo': ('core.html#foo', 'nbdev_mkdocs_test/core.py')}}}
