# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo', 'HelloSayer']

# %% ../nbs/00_core.ipynb 2
from fastcore.utils import patch

# %% ../nbs/00_core.ipynb 4
def foo(): 
    """foo"""
    pass

# %% ../nbs/00_core.ipynb 5
class HelloSayer:
    """Say hello to `to` using `say_hello`"""
    def __init__(self, name): self.name = name
        
    @staticmethod
    def static_method():
        """Do the saying"""
        return "Hello from static_method"
    
    @classmethod
    def class_method(cls):
        """Do the saying"""
        return "Hello from class_method"

# %% ../nbs/00_core.ipynb 6
@patch
def instance_method(self: HelloSayer):
    """Do the saying"""
    return f"Hello {self.name} from instance_method"
