name: Deploy nbdev-mkdocs generated documentation to GitHub Pages

on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: 
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: airtai/workflows/nbdev-mkdocs-ghp@main
